[project]
name = "portfolioanalysistool"
version = "0.1.0"
description = "Analyse stock portfolios"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.3.1",
    "pandas>=3.0.2",
    "polars>=1.39.3",
    "pytest>=9.0.2",
    "spyder-kernels==3.1.*",
    "yfinance>=1.2.0",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]